---
# This playbook deploys an IPA signed certificate to a system
# This requires a kinit by the running process

- name: apply common configuration to all nodes
  hosts: servicetargets
  remote_user: parmstro
  become: yes

  roles:
  - ipasignedcert